### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by kav2k** [liviavinci/Boundary#1]
I would like to use this in my project.

However, without clarification of the license I am wary to do this. I wouldn't use a restrictive copyright license or a restrictive copyleft license (e.g. full-blown GPL, as opposed to LGPL).

http://choosealicense.com/ may help you to pick one, if needed.

**Comment by liviavinci** [comment]
@kav2k I just added a clarification of the license (MIT) in README. Thanks for recommending http://choosealicense.com/ . Let me know if you have other questions.
