### ISSUE TITLE
anchor link in iframe

### ISSUE THREAD

**Issue by mehmetilker** [liviavinci/Boundary#2]
When I click an anchor link in iframe it goes to parent url.
 `<a href="#">aaa</a>`
What I am trying to do is adding a bootstrap tab menu for example...
Do you I need to add something to iframe settings in boundary.js ?

**Comment by liviavinci** [comment]
Hey @mehmetilker , can you please describe the problem with more details?

**Comment by mehmetilker** [comment]
@liviavinci At first I though it is specific to your solution (creating iframe element in extension)
But it is general I problem in iframe I guess. When I load a page within iframe with an anchor element href attribute set "#", it redirects parent page when it is clicked.

For example when I load a tab component shown here in an iframe, when you click second tab, iframe loads parent page instead of show second tab content
https://css-tricks.com/css3-tabs/
