### ISSUE TITLE
Multiple iframes in the same page problem

### ISSUE THREAD

**Issue by felipe-augusto** [liviavinci/Boundary#3]
Hello, I got a problem with multiple iframes in the same page. I am trying to inject a small button in a page, but if the page has already an iframe (or more) it would inject the button in the page and in the iframes. I managed to solve this problem by making a small change in the line 12 of the file `boundary.js`. Replacing this code:

`$("body").append(iframe);`

By this:

```
if (window.self === window.top) {
    $("body").append(iframe);
}
```

Hope this helps.
Thanks!

**Comment by liviavinci** [comment]
@fesnt Thanks a lot! Sorry for some reason I didn't notice your issue. Will amend. Thanks again.

**Comment by liviavinci** [comment]
Fixed
